spring:
  application:
    name: server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-request-size: 3072MB
      max-file-size: 3072MB
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans
swagger2:
  show: true
  group-name: ${spring.application.name}
  base-package: com.heyqing.disk
  title: Hey-Disk-Server docs
  description: Hey-Disk-Server docs
  terms-of-service-url: http://127.0.0.1:${server.port}
  contact-name: heyqing
  contact-url: https://gitee.com/heyqing
  contact-email: heyqing0@126.com
  version: 1.0