spring:
  application:
    name: server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-request-size: 3072MB
      max-file-size: 3072MB
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/hey_disk?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans
swagger2:
  show: true
  group-name: ${spring.application.name}
  base-package: com.heyqing.disk
  title: Hey-Disk-Server docs
  description: Hey-Disk-Server docs
  terms-of-service-url: http://127.0.0.1:${server.port}
  contact-name: heyqing
  contact-url: https://gitee.com/heyqing
  contact-email: heyqing0@126.com
  version: 1.0
mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml